### ISSUE TITLE
Claim your exercise

### ISSUE THREAD

**Issue by samiconductor** [gangstead/comder#2]
To avoid duplicate effort, let everyone know which exercise you're working on.

**Comment by samiconductor** [comment]
I'm doing `EXPRESSION_REGULAR`

**Comment by thomrichardson** [comment]
I'm working on EXPRESSION_REGULAR

**Comment by burin** [comment]
i'm going to work on `FEEL_THE_COERCION`

**Comment by gangstead** [comment]
@samiconductor @thomrichardson the awkwardness is palpable
