### ISSUE TITLE
Add yourself as a contributor to README and credits

### ISSUE THREAD

**Issue by gangstead** [gangstead/comder#7]
@Enmadaio @samiconductor @burin I've made you all collaborators.  

The next step is to make sure you get to share in all the millions of dollars that come with being a workshopper contributor.  This requires that you update the Contributors table in the `README.md` and add a line in `contributors.txt`.

**Comment by burin** [comment]
@gangstead i didn't see an existing `contributors.txt`. Do we need to add one? There are two spots right now: the `README.md` and the `package.json`.

**Comment by gangstead** [comment]
Oops I mean credits.text. good catch on the package.json

**Comment by gangstead** [comment]
I think the package credits are for npm. Credits.text is for in the workshop and readme is for github

**Comment by gangstead** [comment]
Just @samiconductor left.  Make sure to do a pull from upstream first so you add your credits to the other credits.
